include_directories(SYSTEM Encryption/cryptopp564/)

set(CRYPTOPP_HEADER_DIR ${CMAKE_CURRENT_SOURCE_DIR}/Encryption/cryptopp564/)
set(CRYPTOPP_SOURCE_DIR ${CMAKE_CURRENT_SOURCE_DIR}/Encryption/cryptopp564/)


#============================================================================
# Internal compiler options
#============================================================================
# Don't use RPATH's. The resulting binary could fail a security audit.
if (NOT CMAKE_VERSION VERSION_LESS 2.8.12)
  set(CMAKE_MACOSX_RPATH 0)
endif()

# Endianess
#TEST_BIG_ENDIAN(IS_BIG_ENDIAN)
#if(IS_BIG_ENDIAN)
#	add_definitions(-DIS_BIG_ENDIAN)
#endif()

#============================================================================
# Sources & headers
#============================================================================

set(CRYPTOPP_HEADERS    
    ${CRYPTOPP_HEADER_DIR}3way.h
    ${CRYPTOPP_HEADER_DIR}adler32.h
    ${CRYPTOPP_HEADER_DIR}aes.h
    ${CRYPTOPP_HEADER_DIR}algebra.h
    ${CRYPTOPP_HEADER_DIR}algparam.h
    ${CRYPTOPP_HEADER_DIR}arc4.h
    ${CRYPTOPP_HEADER_DIR}argnames.h
    ${CRYPTOPP_HEADER_DIR}asn.h
    ${CRYPTOPP_HEADER_DIR}authenc.h
    ${CRYPTOPP_HEADER_DIR}base32.h
    ${CRYPTOPP_HEADER_DIR}base64.h
    ${CRYPTOPP_HEADER_DIR}basecode.h
    ${CRYPTOPP_HEADER_DIR}bench.h
    ${CRYPTOPP_HEADER_DIR}blake2.h
    ${CRYPTOPP_HEADER_DIR}blowfish.h
    ${CRYPTOPP_HEADER_DIR}blumshub.h
    ${CRYPTOPP_HEADER_DIR}camellia.h
    ${CRYPTOPP_HEADER_DIR}cast.h
    ${CRYPTOPP_HEADER_DIR}cbcmac.h
    ${CRYPTOPP_HEADER_DIR}ccm.h
    ${CRYPTOPP_HEADER_DIR}chacha.h
    ${CRYPTOPP_HEADER_DIR}channels.h
    ${CRYPTOPP_HEADER_DIR}cmac.h
    ${CRYPTOPP_HEADER_DIR}config.h
    ${CRYPTOPP_HEADER_DIR}cpu.h
    ${CRYPTOPP_HEADER_DIR}crc.h
    ${CRYPTOPP_HEADER_DIR}cryptlib.h
    ${CRYPTOPP_HEADER_DIR}default.h
    ${CRYPTOPP_HEADER_DIR}des.h
    ${CRYPTOPP_HEADER_DIR}dh.h
    ${CRYPTOPP_HEADER_DIR}dh2.h
    ${CRYPTOPP_HEADER_DIR}dll.h
    ${CRYPTOPP_HEADER_DIR}dmac.h
    ${CRYPTOPP_HEADER_DIR}dsa.h
    ${CRYPTOPP_HEADER_DIR}eax.h
    ${CRYPTOPP_HEADER_DIR}ec2n.h
    ${CRYPTOPP_HEADER_DIR}eccrypto.h
    ${CRYPTOPP_HEADER_DIR}ecp.h
    ${CRYPTOPP_HEADER_DIR}elgamal.h
    ${CRYPTOPP_HEADER_DIR}emsa2.h
    ${CRYPTOPP_HEADER_DIR}eprecomp.h
    ${CRYPTOPP_HEADER_DIR}esign.h
    ${CRYPTOPP_HEADER_DIR}factory.h
    ${CRYPTOPP_HEADER_DIR}fhmqv.h
    ${CRYPTOPP_HEADER_DIR}files.h
    ${CRYPTOPP_HEADER_DIR}filters.h
    ${CRYPTOPP_HEADER_DIR}fips140.h
    ${CRYPTOPP_HEADER_DIR}fltrimpl.h
    ${CRYPTOPP_HEADER_DIR}gcm.h
    ${CRYPTOPP_HEADER_DIR}gf256.h
    ${CRYPTOPP_HEADER_DIR}gf2n.h
    ${CRYPTOPP_HEADER_DIR}gf2_32.h
    ${CRYPTOPP_HEADER_DIR}gfpcrypt.h
    ${CRYPTOPP_HEADER_DIR}gost.h
    ${CRYPTOPP_HEADER_DIR}gzip.h
    ${CRYPTOPP_HEADER_DIR}hex.h
    ${CRYPTOPP_HEADER_DIR}hkdf.h
    ${CRYPTOPP_HEADER_DIR}hmac.h
    ${CRYPTOPP_HEADER_DIR}hmqv.h
    ${CRYPTOPP_HEADER_DIR}hrtimer.h
    ${CRYPTOPP_HEADER_DIR}ida.h
    ${CRYPTOPP_HEADER_DIR}idea.h
    ${CRYPTOPP_HEADER_DIR}integer.h
    ${CRYPTOPP_HEADER_DIR}iterhash.h
    ${CRYPTOPP_HEADER_DIR}keccak.h
    ${CRYPTOPP_HEADER_DIR}lubyrack.h
    ${CRYPTOPP_HEADER_DIR}luc.h
    ${CRYPTOPP_HEADER_DIR}mars.h
    ${CRYPTOPP_HEADER_DIR}md2.h
    ${CRYPTOPP_HEADER_DIR}md4.h
    ${CRYPTOPP_HEADER_DIR}md5.h
    ${CRYPTOPP_HEADER_DIR}mdc.h
    ${CRYPTOPP_HEADER_DIR}mersenne.h
    ${CRYPTOPP_HEADER_DIR}misc.h
    ${CRYPTOPP_HEADER_DIR}modarith.h
    ${CRYPTOPP_HEADER_DIR}modes.h
    ${CRYPTOPP_HEADER_DIR}modexppc.h
    ${CRYPTOPP_HEADER_DIR}mqueue.h
    ${CRYPTOPP_HEADER_DIR}mqv.h
    ${CRYPTOPP_HEADER_DIR}nbtheory.h
    ${CRYPTOPP_HEADER_DIR}network.h
    ${CRYPTOPP_HEADER_DIR}nr.h
    ${CRYPTOPP_HEADER_DIR}oaep.h
    ${CRYPTOPP_HEADER_DIR}oids.h
    ${CRYPTOPP_HEADER_DIR}osrng.h
    ${CRYPTOPP_HEADER_DIR}panama.h
    ${CRYPTOPP_HEADER_DIR}pch.h
    ${CRYPTOPP_HEADER_DIR}pkcspad.h
    ${CRYPTOPP_HEADER_DIR}polynomi.h
    ${CRYPTOPP_HEADER_DIR}pssr.h
    ${CRYPTOPP_HEADER_DIR}pubkey.h
    ${CRYPTOPP_HEADER_DIR}pwdbased.h
    ${CRYPTOPP_HEADER_DIR}queue.h
    ${CRYPTOPP_HEADER_DIR}rabin.h
    ${CRYPTOPP_HEADER_DIR}randpool.h
    ${CRYPTOPP_HEADER_DIR}rc2.h
    ${CRYPTOPP_HEADER_DIR}rc5.h
    ${CRYPTOPP_HEADER_DIR}rc6.h
    ${CRYPTOPP_HEADER_DIR}rdrand.h
    ${CRYPTOPP_HEADER_DIR}resource.h
    ${CRYPTOPP_HEADER_DIR}rijndael.h
    ${CRYPTOPP_HEADER_DIR}ripemd.h
    ${CRYPTOPP_HEADER_DIR}rng.h
    ${CRYPTOPP_HEADER_DIR}rsa.h
    ${CRYPTOPP_HEADER_DIR}rw.h
    ${CRYPTOPP_HEADER_DIR}safer.h
    ${CRYPTOPP_HEADER_DIR}salsa.h
    ${CRYPTOPP_HEADER_DIR}seal.h
    ${CRYPTOPP_HEADER_DIR}secblock.h
    ${CRYPTOPP_HEADER_DIR}seckey.h
    ${CRYPTOPP_HEADER_DIR}seed.h
    ${CRYPTOPP_HEADER_DIR}serpent.h
    ${CRYPTOPP_HEADER_DIR}serpentp.h
    ${CRYPTOPP_HEADER_DIR}sha.h
    ${CRYPTOPP_HEADER_DIR}sha3.h
    ${CRYPTOPP_HEADER_DIR}shacal2.h
    ${CRYPTOPP_HEADER_DIR}shark.h
    ${CRYPTOPP_HEADER_DIR}simple.h
    ${CRYPTOPP_HEADER_DIR}skipjack.h
    ${CRYPTOPP_HEADER_DIR}smartptr.h
    ${CRYPTOPP_HEADER_DIR}socketft.h
    ${CRYPTOPP_HEADER_DIR}sosemanuk.h
    ${CRYPTOPP_HEADER_DIR}square.h
    ${CRYPTOPP_HEADER_DIR}stdcpp.h
    ${CRYPTOPP_HEADER_DIR}strciphr.h
    ${CRYPTOPP_HEADER_DIR}tea.h
    ${CRYPTOPP_HEADER_DIR}tiger.h
    ${CRYPTOPP_HEADER_DIR}trdlocal.h
    ${CRYPTOPP_HEADER_DIR}trunhash.h
    ${CRYPTOPP_HEADER_DIR}ttmac.h
    ${CRYPTOPP_HEADER_DIR}twofish.h
    ${CRYPTOPP_HEADER_DIR}validate.h
    ${CRYPTOPP_HEADER_DIR}vmac.h
    ${CRYPTOPP_HEADER_DIR}wait.h
    ${CRYPTOPP_HEADER_DIR}wake.h
    ${CRYPTOPP_HEADER_DIR}whrlpool.h
    ${CRYPTOPP_HEADER_DIR}winpipes.h
    ${CRYPTOPP_HEADER_DIR}words.h
    ${CRYPTOPP_HEADER_DIR}xtr.h
    ${CRYPTOPP_HEADER_DIR}xtrcrypt.h
    ${CRYPTOPP_HEADER_DIR}zdeflate.h
    ${CRYPTOPP_HEADER_DIR}zinflate.h
    ${CRYPTOPP_HEADER_DIR}zlib.h)

set(CRYPTOPP_SOURCES
    ${CRYPTOPP_SOURCE_DIR}3way.cpp
    ${CRYPTOPP_SOURCE_DIR}adler32.cpp
    ${CRYPTOPP_SOURCE_DIR}algebra.cpp
    ${CRYPTOPP_SOURCE_DIR}algparam.cpp
    ${CRYPTOPP_SOURCE_DIR}arc4.cpp
    ${CRYPTOPP_SOURCE_DIR}asn.cpp
    ${CRYPTOPP_SOURCE_DIR}authenc.cpp
    ${CRYPTOPP_SOURCE_DIR}base32.cpp
    ${CRYPTOPP_SOURCE_DIR}base64.cpp
    ${CRYPTOPP_SOURCE_DIR}basecode.cpp
    ${CRYPTOPP_SOURCE_DIR}bench1.cpp
    ${CRYPTOPP_SOURCE_DIR}bench2.cpp
    ${CRYPTOPP_SOURCE_DIR}bfinit.cpp
    ${CRYPTOPP_SOURCE_DIR}blake2.cpp
    ${CRYPTOPP_SOURCE_DIR}blowfish.cpp
    ${CRYPTOPP_SOURCE_DIR}blumshub.cpp
    ${CRYPTOPP_SOURCE_DIR}camellia.cpp
    ${CRYPTOPP_SOURCE_DIR}cast.cpp
    ${CRYPTOPP_SOURCE_DIR}casts.cpp
    ${CRYPTOPP_SOURCE_DIR}cbcmac.cpp
    ${CRYPTOPP_SOURCE_DIR}ccm.cpp
    ${CRYPTOPP_SOURCE_DIR}chacha.cpp
    ${CRYPTOPP_SOURCE_DIR}channels.cpp
    ${CRYPTOPP_SOURCE_DIR}cmac.cpp
    ${CRYPTOPP_SOURCE_DIR}cpu.cpp
    ${CRYPTOPP_SOURCE_DIR}crc.cpp
    ${CRYPTOPP_SOURCE_DIR}cryptlib.cpp
    ${CRYPTOPP_SOURCE_DIR}datatest.cpp
    ${CRYPTOPP_SOURCE_DIR}default.cpp
    ${CRYPTOPP_SOURCE_DIR}des.cpp
    ${CRYPTOPP_SOURCE_DIR}dessp.cpp
    ${CRYPTOPP_SOURCE_DIR}dh.cpp
    ${CRYPTOPP_SOURCE_DIR}dh2.cpp
    ${CRYPTOPP_SOURCE_DIR}dll.cpp
    ${CRYPTOPP_SOURCE_DIR}dlltest.cpp
    ${CRYPTOPP_SOURCE_DIR}dsa.cpp
    ${CRYPTOPP_SOURCE_DIR}eax.cpp
    ${CRYPTOPP_SOURCE_DIR}ec2n.cpp
    ${CRYPTOPP_SOURCE_DIR}eccrypto.cpp
    ${CRYPTOPP_SOURCE_DIR}ecp.cpp
    ${CRYPTOPP_SOURCE_DIR}elgamal.cpp
    ${CRYPTOPP_SOURCE_DIR}emsa2.cpp
    ${CRYPTOPP_SOURCE_DIR}eprecomp.cpp
    ${CRYPTOPP_SOURCE_DIR}esign.cpp
    ${CRYPTOPP_SOURCE_DIR}files.cpp
    ${CRYPTOPP_SOURCE_DIR}filters.cpp
    ${CRYPTOPP_SOURCE_DIR}fips140.cpp
    ${CRYPTOPP_SOURCE_DIR}fipsalgt.cpp
    ${CRYPTOPP_SOURCE_DIR}fipstest.cpp
    ${CRYPTOPP_SOURCE_DIR}gcm.cpp
    ${CRYPTOPP_SOURCE_DIR}gf256.cpp
    ${CRYPTOPP_SOURCE_DIR}gf2n.cpp
    ${CRYPTOPP_SOURCE_DIR}gf2_32.cpp
    ${CRYPTOPP_SOURCE_DIR}gfpcrypt.cpp
    ${CRYPTOPP_SOURCE_DIR}gost.cpp
    ${CRYPTOPP_SOURCE_DIR}gzip.cpp
    ${CRYPTOPP_SOURCE_DIR}hex.cpp
    ${CRYPTOPP_SOURCE_DIR}hmac.cpp
    ${CRYPTOPP_SOURCE_DIR}hrtimer.cpp
    ${CRYPTOPP_SOURCE_DIR}ida.cpp
    ${CRYPTOPP_SOURCE_DIR}idea.cpp
    ${CRYPTOPP_SOURCE_DIR}integer.cpp
    ${CRYPTOPP_SOURCE_DIR}iterhash.cpp
    ${CRYPTOPP_SOURCE_DIR}keccak.cpp
    ${CRYPTOPP_SOURCE_DIR}luc.cpp
    ${CRYPTOPP_SOURCE_DIR}mars.cpp
    ${CRYPTOPP_SOURCE_DIR}marss.cpp
    ${CRYPTOPP_SOURCE_DIR}md2.cpp
    ${CRYPTOPP_SOURCE_DIR}md4.cpp
    ${CRYPTOPP_SOURCE_DIR}md5.cpp
    ${CRYPTOPP_SOURCE_DIR}misc.cpp
    ${CRYPTOPP_SOURCE_DIR}modes.cpp
    ${CRYPTOPP_SOURCE_DIR}mqueue.cpp
    ${CRYPTOPP_SOURCE_DIR}mqv.cpp
    ${CRYPTOPP_SOURCE_DIR}nbtheory.cpp
    ${CRYPTOPP_SOURCE_DIR}network.cpp
    ${CRYPTOPP_SOURCE_DIR}oaep.cpp
    ${CRYPTOPP_SOURCE_DIR}osrng.cpp
    ${CRYPTOPP_SOURCE_DIR}panama.cpp
    ${CRYPTOPP_SOURCE_DIR}pch.cpp
    ${CRYPTOPP_SOURCE_DIR}pkcspad.cpp
    ${CRYPTOPP_SOURCE_DIR}polynomi.cpp
    ${CRYPTOPP_SOURCE_DIR}pssr.cpp
    ${CRYPTOPP_SOURCE_DIR}pubkey.cpp
    ${CRYPTOPP_SOURCE_DIR}queue.cpp
    ${CRYPTOPP_SOURCE_DIR}rabin.cpp
    ${CRYPTOPP_SOURCE_DIR}randpool.cpp
    ${CRYPTOPP_SOURCE_DIR}rc2.cpp
    ${CRYPTOPP_SOURCE_DIR}rc5.cpp
    ${CRYPTOPP_SOURCE_DIR}rc6.cpp
    ${CRYPTOPP_SOURCE_DIR}rdrand.cpp
    ${CRYPTOPP_SOURCE_DIR}rdtables.cpp
    ${CRYPTOPP_SOURCE_DIR}regtest.cpp
    ${CRYPTOPP_SOURCE_DIR}rijndael.cpp
    ${CRYPTOPP_SOURCE_DIR}ripemd.cpp
    ${CRYPTOPP_SOURCE_DIR}rng.cpp
    ${CRYPTOPP_SOURCE_DIR}rsa.cpp
    ${CRYPTOPP_SOURCE_DIR}rw.cpp
    ${CRYPTOPP_SOURCE_DIR}safer.cpp
    ${CRYPTOPP_SOURCE_DIR}salsa.cpp
    ${CRYPTOPP_SOURCE_DIR}seal.cpp
    ${CRYPTOPP_SOURCE_DIR}seed.cpp
    ${CRYPTOPP_SOURCE_DIR}serpent.cpp
    ${CRYPTOPP_SOURCE_DIR}sha.cpp
    ${CRYPTOPP_SOURCE_DIR}sha3.cpp
    ${CRYPTOPP_SOURCE_DIR}shacal2.cpp
    ${CRYPTOPP_SOURCE_DIR}shark.cpp
    ${CRYPTOPP_SOURCE_DIR}sharkbox.cpp
    ${CRYPTOPP_SOURCE_DIR}simple.cpp
    ${CRYPTOPP_SOURCE_DIR}skipjack.cpp
    ${CRYPTOPP_SOURCE_DIR}socketft.cpp
    ${CRYPTOPP_SOURCE_DIR}sosemanuk.cpp
    ${CRYPTOPP_SOURCE_DIR}square.cpp
    ${CRYPTOPP_SOURCE_DIR}squaretb.cpp
    ${CRYPTOPP_SOURCE_DIR}strciphr.cpp
    ${CRYPTOPP_SOURCE_DIR}tea.cpp
    ${CRYPTOPP_SOURCE_DIR}test.cpp
    ${CRYPTOPP_SOURCE_DIR}tftables.cpp
    ${CRYPTOPP_SOURCE_DIR}tiger.cpp
    ${CRYPTOPP_SOURCE_DIR}tigertab.cpp
    ${CRYPTOPP_SOURCE_DIR}trdlocal.cpp
    ${CRYPTOPP_SOURCE_DIR}ttmac.cpp
    ${CRYPTOPP_SOURCE_DIR}twofish.cpp
    ${CRYPTOPP_SOURCE_DIR}validat1.cpp
    ${CRYPTOPP_SOURCE_DIR}validat2.cpp
    ${CRYPTOPP_SOURCE_DIR}validat3.cpp
    ${CRYPTOPP_SOURCE_DIR}vmac.cpp
    ${CRYPTOPP_SOURCE_DIR}wait.cpp
    ${CRYPTOPP_SOURCE_DIR}wake.cpp
    ${CRYPTOPP_SOURCE_DIR}whrlpool.cpp
    ${CRYPTOPP_SOURCE_DIR}winpipes.cpp
    ${CRYPTOPP_SOURCE_DIR}xtr.cpp
    ${CRYPTOPP_SOURCE_DIR}xtrcrypt.cpp
    ${CRYPTOPP_SOURCE_DIR}zdeflate.cpp
    ${CRYPTOPP_SOURCE_DIR}zinflate.cpp
    ${CRYPTOPP_SOURCE_DIR}zlib.cpp)

if(MINGW OR WIN32)
	list(APPEND CRYPTOPP_SOURCES ${CMAKE_CURRENT_SOURCE_DIR}/Encryption/cryptopp564/winpipes.cpp)
endif()

set (NGCP_GLOB
    ${NGCP_GLOB}
    ${CRYPTOPP_SOURCES}
    ${CRYPTOPP_HEADERS})
    

    