# Hash file configs
set(HASH_HEADER_DIR ${CMAKE_CURRENT_SOURCE_DIR}/CommProto/include/CommProto/hash/)
set(HASH_SOURCE_DIR ${CMAKE_CURRENT_SOURCE_DIR}/CommProto/src/hash/)

set(COMMPROTO_HASH_HEADERS
  ${HASH_HEADER_DIR}/ngcphash.h)

set(COMMPROTO_HASH_SOURCES
  ${HASH_SOURCE_DIR}/ngcphash.cpp)


set (NGCP_GLOB
  ${NGCP_GLOB}
  ${COMMPROTO_HASH_HEADERS}
  ${COMMPROTO_HASH_SOURCES})